sonar.projectKey=web-components
sonar.projectName=web-components
sonar.projectVersion=1.0

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
